### PR TITLE
project layout

### PR DESCRIPTION
**Pull request by 3rkeen**
This pull request was used to plan the layout of various sections of the project.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
This PR is under Review by: **[TSE] Temitayo Adeleke**

**Comment by lekegitrepo** [comment]
## Great Job @3rkeen and @Zubenna 👍 
I'll like to say you have put a lot of effort into this project. Actually, you need to make some minor but required changes before the project can be approved.

## _Note: you have closed this Pull Request, please Reopen it_

### _Required:_
* [ ] The Pull Request should have a meaningful title and a short description (
[screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png)).
* [ ] The Phone  `<input>`  should be of type `tel` not number ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))

**_If you have any doubt or question contact me on slack._**

**Reviewed by: _Temitayo Adeleke_**

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — COMMENTED** [review]
### Status: Required Changes

**Comment by 3rkeen** [comment]
Hi Temitayo,

Thank you for you feedback.

Please check now that we have fixed all the issues you mentioned.

Thank you.

**Pull request closed without merging**
